os: linux
dist: xenial

sudo: required

git:
  depth: 3

addons:
  apt:
    update:
    - true
    packages:
    - curl
    - pxz
    - wput

before_install:
  - git clone https://github.com/ZeoRexDevs/gcc_linaro_731_toolchain ~/gcc_linaro_731_toolchain/
  - sudo chmod -R a+x ~/gcc_linaro_731_toolchain/*

install: true

script:
  - mkdir out
  - make O=out clean
  - make O=out mrproper
  - export CROSS_COMPILE=~/gcc_linaro_731_toolchain/bin/aarch64-linux-gnu-
  - export ARCH=arm64 
  - export KBUILD_BUILD_USER="fr3aky"
  - export KBUILD_BUILD_HOST="Phantom_Zone"
  - export ARCH_MTK_PLATFORM=mt6753
  - make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE k53v1_64_bsp_defconfig
  - make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j32
  - KERNEL_DIR=$PWD
  - ZIMAGE=$KERNEL_DIR/out/arch/arm64/boot/Image*

after_success:
  - cd $KERNEL_DIR/out
  - travis_wait 30 time tar -I pxz -cf mediatek-oreo-kernel-out-$(date +%Y%m%d).tar.xz *
  - wput mediatek-oreo-kernel-out-$(date +%Y%m%d).tar.xz ftp://"$FTPUser":"$FTPPass"@"$FTPHost"/
  - rm mediatek-oreo-kernel-out-$(date +%Y%m%d).tar.xz
  - curl --upload-file arch/arm64/boot/Image.gz https://transfer.sh/mediatek-oreo-kernel-zImage

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken"
  file_glob: true
  file: $KERNEL_DIR/out/arch/arm64/boot/Image*
  on:
    tags: false
    repo: ZeoRexDevs/mediatek-oreo-kernel
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
