os: linux
dist: xenial

sudo: required

addons:
  apt:
    update:
    - true
    packages:
    - curl
    - tree

before_install:
  - git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 ~/aarch64-linux-android-4.9/
  - sudo chmod -R a+x ~/aarch64-linux-android-4.9/*

install: true

script:
  - mkdir out
  - make O=out clean
  - make O=out mrproper
  - export CROSS_COMPILE=~/aarch64-linux-android-4.9/bin/aarch64-linux-android-
  - export ARCH=arm64 
  - export KBUILD_BUILD_USER="fr3aky"
  - export KBUILD_BUILD_HOST="Phantom_Zone"
  - export ARCH_MTK_PLATFORM=mt6753
  - make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE k53v1_64_bsp_defconfig
  - make O=out ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j16
  - KERNEL_DIR=$PWD/mediatek-oreo-kernel
  - ZIMAGE=$KERNEL_DIR/out/arch/arm64/boot/*Image*

after_success:
  - tree -a $KERNEL_DIR/out >> $KERNEL_DIR/out-tree.log
  - curl --upload-file $KERNEL_DIR/out-tree.log https://transfer.sh/
  - curl --upload-file $ZIMAGE https://transfer.sh/

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GitOAUTHToken"
  file_glob: true
  file: $KERNEL_DIR/out/arch/arm64/boot/*Image*
  on:
    tags: false
    repo: ZeoRexDevs/mediatek-oreo-kernel
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
